# Overlay "local": môi trường chạy trên Kubernetes của Docker Desktop.
# ArgoCD theo dõi thư mục này. Deploy = đổi newTag (CI sẽ tự làm ở Bước 4 của Bài 7).
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcservice

resources:
  - ../../base
  - httproute.yaml

images:
  - name: userservice
    newName: ghcr.io/thinhphamduc/mcservice-userservice
    newTag: 9873bde820d8282e0ec3fc84c0488f40858a4d69
  - name: orderservice
    newName: ghcr.io/thinhphamduc/mcservice-orderservice
    newTag: 9873bde820d8282e0ec3fc84c0488f40858a4d69
  - name: paymentservice
    newName: ghcr.io/thinhphamduc/mcservice-paymentservice
    newTag: 9873bde820d8282e0ec3fc84c0488f40858a4d69
