# Overlay "local": môi trường chạy trên Kubernetes của Docker Desktop.
# ArgoCD theo dõi thư mục này. Deploy = đổi newTag (CI sẽ tự làm ở Bước 4 của Bài 7).
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcservice

resources:
  - ../../base

images:
  - name: userservice
    newName: ghcr.io/thinhphamduc/mcservice-userservice
    newTag: 59375c704624c819936e128e7f6e027b6517a973
  - name: orderservice
    newName: ghcr.io/thinhphamduc/mcservice-orderservice
    newTag: 59375c704624c819936e128e7f6e027b6517a973
  - name: paymentservice
    newName: ghcr.io/thinhphamduc/mcservice-paymentservice
    newTag: 59375c704624c819936e128e7f6e027b6517a973
